# 机器人基础配置 (兼容Windows和Linux)
bot:
  napcat:
    host: "127.0.0.1"  # Napcat服务地址，兼容所有平台
    port: 3001  # Napcat服务端口，兼容所有平台
    access_token: "your_access_token"  # Napcat访问令牌
    # Windows特定配置
    windows:
      service_name: "NapcatService"  # Windows服务名称
    # Linux特定配置  
    linux:
      systemd_service: "napcat.service"  # Linux systemd服务名称

  admin:
    super_users: [123456789]  # 超级管理员QQ号列表
    group_admins: []  # 群管理员列表

# 功能配置 (兼容Windows和Linux)
features:
  session:
    host: "127.0.0.1"  # 会话服务地址，兼容所有平台
    port: 3001  # 会话服务端口，兼容所有平台
    access_token: "your_access_token"  # 会话访问令牌
    # 路径配置使用正斜杠，兼容Windows和Linux
    log_dir: "logs/"  # 日志目录
    data_dir: "data/"  # 数据目录

  sign_in:  # 签到功能配置
    enabled: true  # 是否启用签到功能
    rewards:
      min: 0  # 最小奖励值
      max: 10  # 最大奖励值
    data_file: "data/sign_in.json"  # 签到数据存储路径
    
  chat:
    enabled: true  # 是否启用聊天功能
    provider: "custom"  # AI服务提供商
    debug: false  # 是否启用调试模式
    custom:
      api_key: ""  # 自定义AI服务的API密钥
      ai_endpoint: ""  # 自定义AI服务的URL地址
      model: "default-model"  # 主要使用的模型
      max_tokens: 2000  # 每次响应的最大token数
      temperature: 0.7  # 响应创造性程度
      fallback_models: []  # 备用模型列表
    system_prompt: |  # 系统提示词
      你是一个智能助手，请用专业且友好的方式回答问题。
    presets:  # 预设提示词
      - |
        这是一个预设的提示词示例，用于特定场景的对话。
    access_control:
      enabled: true
      whitelist_enabled: false
      blacklist_enabled: false
      allowed_groups: []
      allowed_friends: []
      blacklist_groups: []
      blacklist_users: []
# 命令配置
  commands:
    enabled: true
    prefix: ""
    case_sensitive: false
    commands:
      - name: "model"
        enabled: true
        plugin: "chat"
        function: "model"
        aliases: ["模型", "切换模型"]
        description: "切换AI模型 (仅管理员)"
        admin_only: true
        
      - name: "签到"
        enabled: true
        plugin: "sign_in"
        function: "sign_in"
        aliases: ["打卡", "check in"]
        description: "每日签到，获取积分"
        
      - name: "帮助"
        enabled: true
        plugin: "basic"
        function: "show_help"
        aliases: ["help", "菜单"]
        description: "显示帮助信息"
        
      - name: "我的积分"
        enabled: true
        plugin: "sign_in"
        function: "show_points"
        aliases: ["积分", "points", "查询积分"]
        description: "查询自己的积分"
        
      - name: "清除记忆"
        enabled: true
        plugin: "chat"
        function: "clear_memory"
        aliases: ["忘记", "forget"]
        description: "清除与你的聊天记忆"
        admin_only: true
        
      - name: "撤回"
        enabled: true
        plugin: "chat"
        function: "withdraw"
        aliases: ["withdraw"]
        description: "撤回指定编号的消息"
        admin_only: true

      - name: "发送信息"
        enabled: true
        plugin: "chat"
        function: "send"
        aliases: ["send"]
        description: "发送消息，用法: /send <消息>，/send friend <QQ> <消息>，/send group <群号> <消息>"
        admin_only: true
        
      - name: "chat"
        enabled: true
        plugin: "chat"
        function: "chat"
        aliases: []
        description: "聊天相关操作，包括发送消息、查看历史等"
        admin_only: true
        
      - name: "测试"
        enabled: true
        plugin: "basic"
        function: "test"
        aliases: ["test"]
        description: "测试命令功能是否正常"
        admin_only: true
        
      - name: "天气"
        enabled: true
        plugin: "extra_features"
        function: "get_weather"
        aliases: ["weather"]
        description: "查询指定城市的天气信息，示例：天气 北京"
        
      - name: "运势"
        enabled: true
        plugin: "extra_features"
        function: "get_fortune"
        aliases: ["fortune", "今日运势"]
        description: "查询今日运势"
        
      - name: "早安"
        enabled: true
        plugin: "extra_features"
        function: "morning_greeting"
        aliases: ["morning", "good_morning"]
        description: "早安问候，记录今天第几个说早安"
        
      - name: "晚安"
        enabled: true
        plugin: "extra_features"
        function: "night_greeting"
        aliases: ["night", "good_night"]
        description: "晚安问候，记录今天第几个说晚安"
        
      - name: "图片"
        enabled: true
        plugin: "extra_features"
        function: "get_random_image"
        aliases: ["pic", "image"]
        description: "获取随机二次元图片，可指定类别，如：图片 女生/男生/风景/壁纸/萌宠"
        
      - name: "点歌"
        enabled: true
        plugin: "extra_features"
        function: "search_music"
        aliases: ["music", "song"]
        description: "搜索并分享音乐，示例：点歌 周杰伦"
        
      - name: "地震"
        enabled: true
        plugin: "extra_features"
        function: "check_earthquake"
        aliases: ["earthquake"]
        description: "查询最新地震信息"
        
      - name: "新闻"
        enabled: true
        plugin: "extra_features"
        function: "get_news"
        aliases: ["news"]
        description: "获取今日热点新闻"
        
      - name: "历史上的今天"
        enabled: true
        plugin: "extra_features"
        function: "get_today_events"
        aliases: ["event", "事件"]
        description: "查询历史上的今天发生的事件"
        
      - name: "设置位置"
        enabled: true
        plugin: "extra_features"
        function: "set_user_location"
        aliases: ["set_location"]
        description: "设置默认天气查询位置，示例：设置位置 北京"

      - name: "Ciallo"
        enabled: true
        plugin: "none"
        function: "none"
        aliases: ["none"]
        description: "作者Ciallo QQ:3688442118"

      - name: "排行榜"
        enabled: true
        plugin: "rank"
        function: "rank"
        aliases: ["rank", "排名"]
        description: "查看排行榜，可选参数：积分、好感度、签到"

      - name: "think"
        enabled: true
        plugin: "chat"
        function: "think"
        aliases: ["思考"]
        description: "显示/隐藏AI思考过程 (仅管理员)"
        admin_only: true
        
      - name: "积分排行"
        enabled: true
        plugin: "rank"
        function: "points_rank"
        aliases: ["积分榜", "points_rank"]
        description: "查看积分排行榜"
        
      - name: "好感度排行"
        enabled: true
        plugin: "rank"
        function: "favor_rank"
        aliases: ["好感榜", "favor_rank"]
        description: "查看好感度排行榜"
        
      - name: "签到排行"
        enabled: true
        plugin: "rank"
        function: "checkin_rank"
        aliases: ["签到榜", "checkin_rank"]
        description: "查看签到排行榜"

  rank:
    points_file: "data/sign_in/points.json"
    favor_file: "data/sign_in/favor.json"
    checkin_file: "data/sign_in/checkin.json"
    default_limit: 90
    max_limit: 100

plugins:
  - name: "basic"
    enabled: true
  - name: "basic"  # 基础功能
    enabled: true
  - name: "chat"   # 聊天功能
    enabled: true
  - name: "sign_in"  # 签到功能
    enabled: true
  - name: "extra_features" # 额外功能
    enabled: true
  - name: "rank"  # 排行榜功能
    enabled: true
